name: local monitor-package-version

on:
  push:
    branches:
      - '*'

  pull_request:
        types: [opened, reopened]

jobs:
  monitor-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: justinj-evans/monitor-package-version@v1.0.1-alpha
        with:
          upgrade: "True"
          downgrade: "True"
          new_package: "True"
          token: "${{ secrets.REPO_ACCESS }}"
          repository: "${{ github.repository }}"
          commit_sha: "${{ github.sha }}"
          existing_sha: "${{ github.event.before }}"

        