name: local monitor-package-version

on:
  push:
    branches:
      - '*'

  pull_request:
        types: [opened, reopened]

jobs:
  monitor-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: justinj-evans/monitor-package-version@latest
        with:
          upgrade: "True"
          downgrade: "True"
          new_package: "True"
        