name: Print Pull Request Number

on:
    push:
      branches:
        - '*'
    pull_request:
          types: [opened, reopened]

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"